# FazAI TUI - Cargo.toml v1.41.0
# Compatível com: Debian/Ubuntu, Fedora/RedHat/CentOS, WSL

[package]
name = "fazai-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.24"
crossterm = "0.27"
